# Header

menu:
  主页: /
  乱语: /categories/乱语/
  研究: /categories/研究/
  关注: /categories/关注/

# SubNav
subnav:
  #github: "#"
  #rss: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #acfun: "#"
  #bilibili: "#"
  #linkedin: "#"
  #google: "https://plus.google.com/111434886305607394058"
  #facebook: "https://www.facebook.com/bailiwulong"
  #twitter: "https://twitter.com/BailiWulong"
  #tumblr: "https://www.tumblr.com/blog/bailiwulong"
  #weibo: "https://weibo.com/5349429655/profile?topnav=1&wvr=6&is_all=1"
  #zhihu: "https://www.zhihu.com/people/dr-dontknow"
  qq: "http://wpa.qq.com/msgrd?v=3&uin=1306015093&site=qq&menu=yes"
  mail: "http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=1306015093@qq.com"
  qzone: "http://1306015093.qzone.qq.com/"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.ico

#你的头像url
avatar: /img/1306015093.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false
#"b0afd35b78764c11b2bfca6676df42ff"

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、友言,uyan="2139744"
uyan: false

#6、来必力
livere: "MTAyMC8zMzIzNy85Nzk0"

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '文章'
  friends: '友链'
  aboutme: '关于'

friends:
#  Litten的博客: http://litten.me/
#  2ch中文网: http://2chcn.com/
#  硅谷黑科技: http://chuansong.me/account/guiguheikeji
#  推酷资讯网: http://www.tuicool.com/
  知乎 -发现更大的世界: https://www.zhihu.com/
  36氪 -让部分人先看到未来: http://36kr.com/
  今日头条 -最新的全球资讯: https://www.toutiao.com/
  脑壳网 -有趣的智力烧脑题库: http://www.naokr.com/

aboutme: 喜欢心理学……<br><br>更喜欢逻辑推理……<br><br>喜欢科幻作品……<br><br>更喜欢物理科普……<br><br>喜欢神秘组织……<br><br>更喜欢传言传说……<br><br>喜欢古建筑……<br><br>更喜欢传统文化……<br><br>喜欢一切有趣的东西……<br><br>总之什么都想去了解，又什么都不深究……<br><br>By：无知の人